name: Image Size Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-images:
    name: Image Size Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Image Sizes
        uses: ./.github/actions/image-size-check
